### ISSUE TITLE
Send message modal not consistent 

### ISSUE THREAD

**Issue by KrishPraba** [NilaanL/webogram#1]

**Comment by NilaanL** [comment]
![image](https://user-images.githubusercontent.com/46640506/119931570-3d0e8880-bf9f-11eb-96e0-140a4b1c5ef4.png)

**Comment by NilaanL** [comment]
![image](https://user-images.githubusercontent.com/46640506/119931593-47308700-bf9f-11eb-9c48-9d39638575ed.png)
